-- +migrate Up

CREATE TABLE IF NOT EXISTS products(
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description text,
	price DOUBLE PRECISION NOT NULL,
    image_url TEXT,
	create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);