CREATE TABLE products(
	id BIGSERIAL PRIMARY KEY,
	tittle VARCHAR(255) NOT NULL,
	description text,
	price DOUBLE PRECISION NOT NULL,
    img_url TEXT,
	create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);